### ISSUE TITLE
Ag-grid icons displayed as squares instead of icons

### ISSUE THREAD

**Issue by fredrikleknes** [equinor/fusion-react-components#1029]
When loading our app (spinedatasheet) in the fusion environments, the ag-grid icons are displayed as squares instead of how they should appear. When we run the app locally this does not happen so the icons appear as intended. This issue started to appear 1-2 weeks ago. 

fusion-ci:
![image](https://github.com/equinor/fusion-react-components/assets/22823836/6ca17346-df2b-4226-a3a7-c895635f93a7)

local environment:
![image](https://github.com/equinor/fusion-react-components/assets/22823836/07454941-e7a4-420b-9957-6eedbe734e38)

In ci the ag icon font-family seems to be overridden by Equinor sans-serif:
![image](https://github.com/equinor/fusion-react-components/assets/22823836/209f101a-fcbd-45c2-971b-a6f1e2772074)

While locally the ag-icon-font-family is used:
![image](https://github.com/equinor/fusion-react-components/assets/22823836/55073995-0a73-4e64-be0b-e04c72a24233)

If i disable the Equinor, sans-serif font-family in ci, the grid icons appear correct:
![image](https://github.com/equinor/fusion-react-components/assets/22823836/26042c5f-c93e-4428-8c70-6d8f32d62577)

**To Reproduce**
1. Go to https://fusion-s-portal-ci.azurewebsites.net/apps/spinedatasheet
2. Select the Snøhvit Future project
3. See the icon bug

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]

**Additional context**
The same issue is reported at https://github.com/ag-grid/ag-grid/issues/3376 but it seems not to be a bug with ag-grid itself, rather the font-family as explained above

**Comment by aigelonic** [comment]
I remember we had some issues around this too and we needed to "override" some styling to be able to move forward.
If I remember correctly this PR outlines somewhat we did:
* https://github.com/equinor/fusion-pitstop-app/pull/946

**Comment by fredrikleknes** [comment]
@aigelonic Thanks! Will try that. However i see the overrides were removed in a later PR. Do you know the reason for that?

**Comment by aigelonic** [comment]
So right you are 😸 
It was changed later on in https://github.com/equinor/fusion-pitstop-app/pull/1075

Then a new version of [@equinor/fusion-react-ag-grid-styles@29.3.14](https://github.com/equinor/fusion-react-components/releases/tag/%40equinor%2Ffusion-react-ag-grid-styles%4029.3.14) had come out and that seemed to fix the issue _for our_ case.

I have not yet tried the latest & greatest version of the styling dependency yet, so cannot say if we again have issues there
(or it might be that you are on a older version of the styling-lib?)

**Comment by fredrikleknes** [comment]
Ah yeah i see that now. I just tried using the exact same versions as you guys but the issue remains on our end. I guess i'll try the overrides while waiting for a permanent fix

**Comment by fredrikleknes** [comment]
Updating to the latest versions plus changing themes from
`className="ag-theme-alpine ag-theme-datasheetTable"` to `className="ag-theme-alpine-fusion"`
has resolved the issue

I guess this isn't a bug then, as this theme is actually the correct one, according to https://github.com/equinor/fusion-react-components/blob/main/packages/ag-grid-styles/README.md
