### ISSUE TITLE
Storybook: Skeleton page seems broken

### ISSUE THREAD

**Issue by aigelonic** [equinor/fusion-react-components#1032]
**Describe the bug**
Navigating to/opening the Storybook for `Skeleton` results in a blank page: https://equinor.github.io/fusion-react-components/?path=/docs/data-skeleton--page.

**To Reproduce**
1. Go to https://equinor.github.io/fusion-react-components/?path=/docs/data-skeleton--page
2. See blank page

**Expected behavior**
Storybook for Skeleton component should be shown.

**Screenshots**
![image](https://github.com/equinor/fusion-react-components/assets/9586805/aa1f4447-d6bb-4c5e-a8b7-bac198a7d766)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser: [Brave] / [Edge]
 - Version [1.58.135] / [117.0.2045.47]

**Additional context**
Observing exception in the Developer Console, unsure if actually related:
```js
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Vg (mwc-textfield-base.js:307:1)
    at mwc-textfield-base.js:307:1
    at fi (mwc-textfield-base.js:307:1)
    at ck (mwc-textfield-base.js:307:1)
    at bk (mwc-textfield-base.js:307:1)
    at ak (mwc-textfield-base.js:307:1)
    at Tj (mwc-textfield-base.js:307:1)
    at Lj (mwc-textfield-base.js:307:1)
    at mwc-textfield-base.js:307:1
    at exports.unstable_runWithPriority (mwc-textfield-base.js:307:1)
```

Core backlog ref: [AB#47910](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/47910)

**Comment by AndrejNikolicEq** [comment]
We are currently working on updating Storybook to version 7, which will fix issue

**Comment by HansDahle** [comment]
This seems to be fixed when checking story book link.
