### ISSUE TITLE
Person: Suppress CORS errors during local development

### ISSUE THREAD

**Issue by aigelonic** [equinor/fusion-react-components#1033]
**Is your feature request related to a problem? Please describe.**
When doing local development and using a Person-component, we see a lot of exceptions being thrown in the developer console.
This is very noisy and makes local debugging a lot harder. Especially in our case where we have a table of 20+ `PersonListItem` components, where each will throw multiple errors.

**Describe the solution you'd like**
Either allow local development (e.g. http://localhost) in the CORS setup or suppress the exceptions being shown; perhaps using a setting (which _defaults_ to suppressing the exceptions).
The end goal is having _no_ exceptions of this type during local development (or any other environments).

**Describe alternatives you've considered**
Going ahead and use the Person-components as-is, but concluded that the noise was to big to use them at this time.

**Additional context**
We are doing the following:
```typescript
<PersonListItem size="small" azureId="36fe5877-bba5-43ee-9ee5-6f795b5f70a8"/>
```
which yields the errors
```javascript
Access to fetch at 'https://fusion-s-portal-ci.azurewebsites.net/images/profiles/36fe5877-bba5-43ee-9ee5-6f795b5f70a8' (redirected from 'https://fusion-s-people-ci.azurewebsites.net/persons/36fe5877-bba5-43ee-9ee5-6f795b5f70a8/photo?api-version=1.0') from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
and then right after
```javascript
GET https://fusion-s-portal-ci.azurewebsites.net/images/profiles/36fe5877-bba5-43ee-9ee5-6f795b5f70a8 net::ERR_FAILED
``` 
and then
```javascript
usePersonResolver.tsx:23 TypeError: Failed to fetch
    at Observable._subscribe (fetch.js:32:1)
    at Observable._trySubscribe (Observable.js:38:1)
    at Observable.js:32:1
    at errorContext (errorContext.js:19:1)
    at Observable.subscribe (Observable.js:23:21)
    at switchMap.js:14:22
    at OperatorSubscriber._this._next (OperatorSubscriber.js:15:1)
    at Subscriber.next (Subscriber.js:34:1)
    at tap.js:18:1
    at OperatorSubscriber._this._next (OperatorSubscriber.js:15:1)
```
(so, at least three exceptions per `PersonListItem` on the page)

**Comment by HansDahle** [comment]
Is this still an issue? I can not see that i get the same error when trying locally.

**Comment by aigelonic** [comment]
> Is this still an issue? I can not see that i get the same error when trying locally.

I just tested locally and cannot seem to reproduce this issue anymore 👍 

I'll close this issue.
