### ISSUE TITLE
Issue with hovering on custom tooltips

### ISSUE THREAD

**Issue by v3gard** [equinor/fusion-react-components#1148]
**Describe the bug**
If custom tooltips are required, hovering doesn't work as expected as the "ease-out" fade transition on the hiding element fails to run.

A workaround is to add the following class style: 
```css
[class*="ag-tooltip-hiding"] {
        display: none;
    }
```

**To Reproduce**
1. Create an AG grid table
2. Add a custom tooltip
3. Add fusion styling
4. See example [here](https://github.com/equinor/fusion-cpr-app/blob/main/src/components/AgGrid/CprAgGrid.tsx).

**Expected behavior**
Ease-in and Ease-out transition works "out of the box", just in the official [demos](https://www.ag-grid.com/javascript-data-grid/component-tooltip/).

**Screenshots**
|Issue|Workaround|
|-|-|
|![aggrid_tooltip_issue](https://github.com/equinor/fusion-react-components/assets/343078/f43d0deb-dd6a-4eaf-8bc4-a5a4744a052a)|![aggrid_tooltip_workarond](https://github.com/equinor/fusion-react-components/assets/343078/487647c6-c9b8-4fbb-b504-fe8ac462a357)|

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 118.0.5993.89

**Comment by odinr** [comment]
created a [PR](https://github.com/equinor/fusion-react-components/pull/1325), will this fix your issue. Will this affect anyone not using custom tooltips (except fading out)?

can create a snapshot for testing if needed?

> not to familiar with AG-Grid but can have @eikeland have a look

**Comment by v3gard** [comment]
> can create a snapshot for testing if needed?
@odinr: Ja, takk. Tar gjerne en pakkereferanse som vi kan teste via npmjs

**Comment by eikeland** [comment]
@v3gard Do the issue persist when setting attribute ``tooltipHideDelay={0}``?

**Comment by odinr** [comment]
created a snapshot [ @equinor/fusion-react-ag-grid-styles@issue-1148](https://www.npmjs.com/package/@equinor/fusion-react-ag-grid-styles/v/0.0.0-issue-1148-20240109090014)

**Comment by v3gard** [comment]
@eikeland @odinr It seems the issue is solved in the newest version of the involved packages, and that we can remove our local hack. I tested this using the CPR app with [this package.json](https://github.com/equinor/fusion-cpr-app/blob/7776631891b71f1f359f631077438a5162b27970/package.json). I.e. the fade-out effect has started working (as it does in vanilla AG Grid without Fusion styling)

![fixed-activities](https://github.com/equinor/fusion-react-components/assets/343078/206dc452-445f-4df7-95cb-6d3fc7dfcea8)


* AG-Grid: 30.2.1
* fusion-framework-module-ag-grid: 30.2.0
* fusion-react-ag-grid-styles: 30.2.0

![image](https://github.com/equinor/fusion-react-components/assets/343078/59c04112-af7d-4759-abcc-1e0a5259fc9e)

This means that there's no need for the snapshot you created @odinr.

Can you also confirm this @AndreasPresthammer?
1. We can [remove our local hack](https://github.com/equinor/fusion-cpr-app/blob/7776631891b71f1f359f631077438a5162b27970/src/components/AgGrid/CprAgGrid.less#L4).
2. Custom tool tips still works (without the wonky UI error as initially described in this issue)

In that case, we can close this ticket.

**Comment by AndreasPresthammer** [comment]
@v3gard yes, it seem to work fine now 👌

**Comment by odinr** [comment]
@v3gard @AndreasPresthammer, so it works now without the css hack in https://github.com/equinor/fusion-react-components/pull/1325?
