### ISSUE TITLE
PersonListItem pop-over causes scrollbar

### ISSUE THREAD

**Issue by estoksam** [equinor/fusion-react-components#1293]
**Describe the bug**
When a PersonListItem is a certain distance away from the bottom of the screen, it will choose to display the pop-over beyond the current length of the page, causing a scrollbar to appear.

The behavior I see suggests an incorrect calculation of the pop-over height causing the component to think it has enough space below when it hasn't.

**To Reproduce**
I have created an example in https://codesandbox.io/p/sandbox/optimistic-napier-863sl5. Using absolute position isn't necessary to trigger this issue. Anything that places the PersonListItem close to the end of the page is sufficient.

1. Show a PersonListItem close to the bottom of the page. If it's too close, it will correctly show the pop-over above the PersonListItem. If it's too far away, it will correctly show the pop-over below the PersonListItem. You may have to experiment with the exact distance.
2. Hover over the PersonListItem to have it show the pop-over.

**Expected behavior**
The pop-over should be shown just above the bottom of the page.

**Screenshots**

Correct (80px from the bottom):
![image](https://github.com/equinor/fusion-react-components/assets/64833421/0603ddfa-e1f0-41b7-996b-ad693e731251)

Incorrect (130px from the bottom):
![image](https://github.com/equinor/fusion-react-components/assets/64833421/126ed74c-2ed4-4813-a552-9ef8acd900d9)

Correct (180px from the bottom):
![image](https://github.com/equinor/fusion-react-components/assets/64833421/1d38e7de-0966-4c09-a86d-2eed7a857d37)

**Desktop**
 - OS: Windows
 - Browser: Firefox 120 and Edge 120 (not a typo, I have version 120 of both)

**Comment by HansDahle** [comment]
So expected behaviour is that the popup should chose a direction based on available room. e.g. in the sandbox example the popup should be directed upwards.

This is also the behaviour i would expect.

We have a focus now on getting the people-feature ready for a v1 release. 
I have reported multiple observations and concerns.. 

Will leav issue open and include reference to backlog item when one is defined.

**Comment by HansDahle** [comment]
AB#48493

**Comment by asbjornhaland** [comment]
This has been released in the portal and should be resolved.

**Comment by estoksam** [comment]
I can confirm that the issue is fixed in my sandbox, and it also seems to be fixed in https://fusion-s-portal-ci.azurewebsites.net/apps/corporate-project-review/. Thank you
