### ISSUE TITLE
PersonAvatar Contact card hidden when used in AgGrid cell

### ISSUE THREAD

**Issue by Jonathanio123** [equinor/fusion-react-components#1431]
**Describe the bug**
Contact Card is being rendered bellow AgGrid / hidden behind AgGrid

**To Reproduce**
Create a CellRenderer with a PersonAvatar within and enable trigger on hover. Hover over with mouse and see that the contact card is not shown properly

**Expected behavior**
That the contact card is shown above aggrid

**Screenshots**
![chrome_BnGBQxt8H8](https://github.com/equinor/fusion-react-components/assets/73334350/5f5aa8b1-e115-4d41-b0c2-b3e55a5ad460)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version Chrome Version 121.0.6167.85 (Official Build) (64-bit)

**Additional context**

**Comment by AndrejNikolicEq** [comment]
We are planning of creating separate component for AGGrid that will allow user to use person components and it will also include sort and filter.
In the meantime, there is a workaround with using `<PersonCard />` as **tooltipComponent** in AGgrid.

You can find working example in [Person cell definition - Contract Personnel](https://github.com/equinor/fusion-core-apps/blob/main/apps/contract-personnel/src/components/table/person-col-def.ts)

**Comment by Jonathanio123** [comment]
That's good to know, I'll take a look at the workaround in the meantime  👍

Thanks for the response

**Comment by AndrejNikolicEq** [comment]
Hello, @Jonathanio123 

good news :sparkles:  now we have working component that solves this issue :tada:
[@equinor/fusion-react-ag-grid-person-cell](https://equinor.github.io/fusion-react-components/?path=/docs/ag-grid-person-cell-docs--docs)

You can see working example in [Contract Personnel - Delegate table](https://github.com/equinor/fusion-core-apps/blob/main/apps/contract-personnel/src/components/tables/delegate/DelegateTable.tsx#L60)
