### ISSUE TITLE
Update node version (at least LTS)

### ISSUE THREAD

**Issue by odinr** [equinor/fusion-react-components#1460]
**ERR_PNPM_UNSUPPORTED_ENGINE  Unsupported environment (bad pnpm and/or Node.js version)**

Your Node version is incompatible with "/Users/odin.rochmann/dev/fusion/fusion-web-components".

Expected version: ^18
Got: v20.11.0

This is happening because the package's manifest has an engines.node field specified.
To fix this issue, install the required Node version.**

- [ ] update package.json node version
- [ ] update github actions

**Comment by asbjornhaland** [comment]
Is this issue in the wrong repo, @odinr ?

**Comment by asbjornhaland** [comment]
Looks like this is already done by @eikeland
