### ISSUE TITLE
[Button] Missing disabled styling

### ISSUE THREAD

**Issue by grynag** [equinor/fusion-react-components#151]
There is minimal difference between a disabled and enabled button: 
![fe4faade-d5aa-4b37-b8fb-998add8eb568](https://user-images.githubusercontent.com/56074883/141472929-6cbcb183-dc13-4f1b-8d82-c2717cd902a8.jpg)

In eds the buttons are grey when disabled: 
![image](https://user-images.githubusercontent.com/56074883/141473024-f53fc2c6-b5b2-4fa0-9822-9353e867da30.png)

https://eds-storybook-react.azurewebsites.net/?path=/docs/components-button--default#all

**Comment by grynag** [comment]
Disabled outlined buttons looks like this: 
![image](https://user-images.githubusercontent.com/56074883/145551934-94f8b05a-c742-4276-bcd3-b853cc3490ec.png)
😬

**Comment by odinr** [comment]
@grynag closer du denne når de pusher?

**Comment by grynag** [comment]
FYI @thomasFjorstad 👍
