### ISSUE TITLE
[Radio]: Disabled styling not correct

### ISSUE THREAD

**Issue by ghost** [equinor/fusion-react-components#157]
A disabled radio button looks like this: 
![image](https://user-images.githubusercontent.com/56074883/143221608-ba9252ed-6b41-41aa-8715-4bb05d46aaca.png)

But it should look like this: 
![image](https://user-images.githubusercontent.com/56074883/143221650-725bf222-bc95-4559-8f98-a26f22bd63a3.png)

**Comment by AndrejNikolicEq** [comment]
Fixed.
