### ISSUE TITLE
[Datepicker] Year picker - list the years in columns instead of rows.

### ISSUE THREAD

**Issue by LottevdBerg-OT** [equinor/fusion-react-components#33]
So for example 2017, 2018, 2019, 2020 below each other in the first column, 2021, 2022, 2023, 2024 in the second column

**Comment by LottevdBerg-OT** [comment]
Jeg ser at Material har listet ut årene i rader, men synes selv at det virket forvirrende. Hva tenker dere? 
Dette gjelder også litt for Month picker

**Comment by maoft** [comment]
We should keep the following format of showing the year picker as rows as this is how react-datepicker is structured and it is difficult to change it. If Material follows the same pattern we can assume it as best practice. If we are to recreate the date picker in the future we will bring up this discussion again.
