### ISSUE TITLE
[Datepicker] - Input field placeholder text in enabled and active state.

### ISSUE THREAD

**Issue by LottevdBerg-OT** [equinor/fusion-react-components#34]
Should the placeholder text indicate the date format, when the input field is active? 
So at the ´dates´ picker, the text could change from ´Select date´ in the enabled state, to ´dd/mm/yyyy´ in the active state.  At the date range picker the text could be changed from ´Select date range (from-to)´ in enabled state, to ´dd/mm/yyyy-dd/mm/yyyy´ in active state.

**Comment by maoft** [comment]
Fixed in #38
