### ISSUE TITLE
[FilterPane] prerequisite components 

### ISSUE THREAD

**Issue by olerichard** [equinor/fusion-react-components#37]
To move the new filter pane component as is from Swcr this repo, the following components needs to be added from Fusion Components. 

Button,
IconButton,
TextInput,
SelectionControls (checkbox,radionbutton),
Chip,

Nice to have : 
(searchable)DropDown

Some standard way to handle Icons. 
Like the useIcon hook. 
this components uses: 
CloseIcon, PaginationArrow from fusion component. 
Also a few that has been added from EDS.

**Comment by odinr** [comment]
@olerichard, @MatsGA 
We are working on the new components [@see](https://github.com/equinor/fusion-web-components/issues)
We are going to prioritise the elements in you list
