### ISSUE TITLE
useStyles doesn't vertically align the table content

### ISSUE THREAD

**Issue by v3gard** [equinor/fusion-react-components#436]
**Describe the bug**
`useStyles` doesn't vertically align the table content similar to what the (now deprecated) `useAgGridStyles` does. It seems that this is because the styles provided for AG grid doesn't render in Chrome.

**To Reproduce**

|-|useStyles|useAgGridStyles|
|-|-|-|
|UI|![image](https://user-images.githubusercontent.com/343078/197748377-417f3bfc-9b1b-465e-9030-d0be3810090f.png)|![image](https://user-images.githubusercontent.com/343078/197748513-cd9777f6-2def-424b-bddd-a9ca304c0bd4.png)|
|Console|![image](https://user-images.githubusercontent.com/343078/197748680-6ecb840c-277d-4d6e-808a-4841709b5d38.png)|![image](https://user-images.githubusercontent.com/343078/197748707-82ce7f0e-26ad-4fc8-b98b-fd1e00429863.png)|

1. Call `useStyles` from `@equinor/fusion-react-ag-grid-styles` version `0.4.4`
2. 💥 

**Expected behavior**
See `useAgGridStyles` from deprecated library `@equinor/fusion-react-ag-grid-addons`, ref example above.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 106.0.5249.119

**Comment by eikeland** [comment]
The styles are not globally injected as a file anymore.
To attach the styles to your ag-grid component, add `useStyles.root` as a className to the wrapper. 
Notice the theme name is now *ag-theme-alpine-fusion*.

eks:
```jsx
<div className={clsx(useStyles().root, 'ag-theme-alpine-fusion')}>
  <AgGridReact {...props} />
</div>
```

We have another open issue concerning the loading of the ag-grid icon font `agGridAlpine`. issue #438. 
For the time being icons currently do not work in the ui.

I will also create an issue to update the package readme with correct usage information.

Sorry for your inconvenience.
