### ISSUE TITLE
[Context selector]:  Enhancement's

### ISSUE THREAD

**Issue by Noggling** [equinor/fusion-react-components#498]
I have a couple of things regarding the context selector that is needed.
most of them are communicated to member in the core team, and may be fixed but 
I'm creating this issue to be sure thigs will be adresser.

1. Context Provider needs to be exposed, but would be nice if Search Provider is wrapped and the components is given propper prop types.
2. Return type of the resolver would be nice.
3.  Need the ability to add onClick handler to icon or any item in the context selector list.

**Comment by eikeland** [comment]
Fixed 1 and 2 in #499
