### ISSUE TITLE
Selected date on datepicker showing a label wich is presumably unintended

### ISSUE THREAD

**Issue by AgeAKristiansen** [equinor/fusion-react-components#591]
**Describe the bug**
Newest version of the datepicker shows a label when you select a date wich must be unintended. 
I do believe it is because of the newest version of react-datepicker package that is used.

**To Reproduce**
1. Have a fresh install of newest datepicker
2. Select a date
3. See label showing up at the top.

**Expected behavior**
The date that is inside the input field should be enough.

**Workaround**
I got it to work as intended by adding react-datepicker version 4.9 to our package.json instead of 4.10 wich it resolves to.

**Comment by odinr** [comment]
This "feature" most likelikely came with the update of the under laying package, this should have been picked up by chromatic....
Update the snapshot so it tracks changes like this
