### ISSUE TITLE
Stepper: `flex-direction` changed to `column`

### ISSUE THREAD

**Issue by v3gard** [equinor/fusion-react-components#921]
**Describe the bug**
Not really a bug, just an observation that the appearance has changed slightly. This was unexpected (but accepted!) by yours truly, so just checking if this is desired behavior.

Note the before and after below. The `flex-direction` seems to have changed from `column` to `row`.

![image](https://github.com/equinor/fusion-react-components/assets/343078/e8f948e3-16fd-469c-8529-2e797eb25b37)

**To Reproduce**
1. Compare[ Storybook on fusion-react-stepper](https://equinor.github.io/fusion-react-components/?path=/docs/examples-stepper--component) with the legacy stepper in [fusion-components](https://equinor.github.io/fusion-components/?path=/story/general-stepper--default).
2. Observe that the title is now positioned below the icon.

**Expected behavior**
No changes in appearance from before.

**Screenshots**
See above.

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: 114.0.5735.199 (Offisiell delversjon) (64-bit) (cohort: Stable)

**Comment by AndrejNikolicEq** [comment]
Yes, talked with the designer and those are the new designs, [FIgma - Stepper](https://www.figma.com/file/zPXt8fVbpBPZuDT3HszVEl/Fusion-Component-Library-(TBD)?type=design&node-id=198-40211&mode=design&t=ByDYBBm5GhlHPRjQ-0) but now that you mentioned it @v3gard I can add a property so we can change between those two

**Comment by odinr** [comment]
@AndrejNikolicEq if this is done, close the issue
