### ISSUE TITLE
[Sidesheet] Sidesheet header is hidden behind fusion top-bar

### ISSUE THREAD

**Issue by Sinrefvol** [equinor/fusion-react-components#966]
**Describe the bug**
Sidesheet component's header is hidden behind fusion top-bar. No access to "close button", title or description of the sidesheet.

**To Reproduce**
1. Go to [Cvp-maturity-matrix](https://352.cvp-pr.fusion-dev.net/9b61844d-66ce-4782-91d7-0e88f18e78b9/bids/8288dba7-b2a8-4d95-998f-1cb50f502d89?step=Overview)
2. Click on "1.1 Asset strategy" line in the table. A sidesheet should open.
4. See that the header is hidden behind fusion top-bar

**Expected behavior**
Header should be visible below the fusion topbar.

**Screenshots**
<img width="1241" alt="image" src="https://github.com/equinor/fusion-react-components/assets/43452613/8f341911-5265-49a6-a55d-7a74adee929d">

**Desktop (please complete the following information):**
 - OS: Windows 11h2
 - Browser [Edge , Chrome]
 - Version [Edge v.116.0.1938.62, Chrome v. 116.0.5845.111]

**Comment by odinr** [comment]
@Noggling 
This is feature developed by @Noggling, any suggestions

**Comment by stephane-vanraes** [comment]
I have been running into the same problem
A workaround for now is to wrap the entire content of the sidesheet in a div and move it down with cs
```css
[class*="Content"] > div {
  top: var(--header-height, 0);
}
```

An actual solution would probably involve adding this _moving down_ to the actual sidesheet content class itself.

**Comment by Noggling** [comment]
@odinr A potensial fix can be in the SidesheetBase.tsx file all the following: 


```TS
export const StyledSideSheet = styled.div`
  height: calc(100vh - var(----header-height));
  position: fixed;
  top: var(--header-height);
  transition: right 10s;
  animation: Animation ease 0.3s;
  right: 0px;

  @keyframes Animation {
    0% {
      right: -500px;
    }
    100% {
      right: 0px;
    }
  }
`;
```

**Comment by Jonathanio123** [comment]
With @stephane-vanraes's workaround it worked but the bottom part of the sidesheet got hidden under the screen and it was not possible to scroll further down. So adding this fixed it.
```TypeScript
export const SideSheetContentWrapper = styled.div`
  margin-bottom: var(--header-height, 0);
`;
```
And then wrapping the sidesheet inner content like this:

```TypeScript
<SideSheet.Content>
  <SideSheetContentWrapper>
    ... Sidesheet content
    ...
  </SideSheetContentWrapper>
</SideSheet.Content>
```

This is just a workaround but works well for now at least
