### ISSUE TITLE
AG-Grid should be able to interract with fusion compact mode

### ISSUE THREAD

**Issue by adukstad** [equinor/fusion-react-components#968]
**Is your feature request related to a problem? Please describe.**
Compact mode has no effect on ag-grid. 
**Describe the solution you'd like**
I would like the option to have ag-grid toggle density based on Fusion compact mode. Not sure the event from the compact mode toggle is exposed to us anymore (?)
**Describe alternatives you've considered**
Making our own implementation of compact mode and therefore bypassing the issue (but not working with the fusion compact mode)

**Comment by odinr** [comment]
For now we don`t have a port for the "userconfig" from the previous FusionAPI, but there is a issue for [persisting state](https://github.com/equinor/fusion-framework/issues/1258) in the framework, once that is complete, we can implement a user settings moudle

for now, this code will du what the previous hook did:
```ts
const settings = window['74b1613f-f22a-451b-a5c3-1c9391e91e68'].settings;
cosnt useCoreSetting = () => {
  const [state, setState] = useState(settings.core.toObject())
  useEffect(() => settings.core.on('change', setCoreSettings), [setCoreSettings]);
  return state;
}

const {displayType} = useCoreSetting();
if(displaytype === 'Compact'){
  ....
}
```

we will keep you updated, thanks for the suggestion

**Comment by odinr** [comment]
should be done in https://github.com/equinor/fusion-framework/issues/1258
