### ISSUE TITLE
Context selector dropdown is invisible and overlaying (but clickable) when selecting context through url.

### ISSUE THREAD

**Issue by fykou** [equinor/fusion-react-components#969]
**Describe the bug**
When selecting a context by entering a url eg. `/apps/ell/82a91aff-0572-4221-8a62-a7fac0b3004a/11kv/normalOperation` the context dropdown is overlaying content underneath and it's not clickthrough.
![image](https://github.com/equinor/fusion-framework/assets/54535198/13adbec8-c990-4e91-adf6-dae9ca69e40e)

**Environment**

- OS: windows
- 18

**To Reproduce**
Enter any app and context by url and inspect the element (or try to click on something underneath.

**Expected behavior**
Expect context dropdown to not overlay content.

**Stacktrace**
N/A

**Additional context**
The invisible dropdown list can be closed by clicking on it. but it requires users to click twice to click on a button underneath the overlay. 
When selecting the context by clicking the context selector, searching and clicking on the dropdown list, this does not occour

**Comment by odinr** [comment]
@Hoyby , thanks for the ticket, we will look into this

@eikeland can you have a look at this

**Comment by eikeland** [comment]
@Hoyby i can not reproduce this. 
Can you specify the branch of the ELL app you are experiencing this issue on.
