### ISSUE TITLE
PersonSelect: Error: No resolver resolved the request

### ISSUE THREAD

**Issue by Jonathanio123** [equinor/fusion-react-components#986]
**Describe the bug**
When searching for a person the error "Error: No resolver resolved the request" is shown

**To Reproduce**
In our case we simply tried to replace a PersonPicker with PersonSelect.

**Expected behavior**
Works like PersonPicker(?)

**Screenshots**
![image](https://github.com/equinor/fusion-react-components/assets/73334350/acdac860-a5d1-4e3e-b02b-093438494cdd)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: 117.0.2045.43 (Official build) (64-bit)

**Additional context**
We are in the process of migrating away from Fusion-Components. We are trying to change out the old PersonPicker with PersonSelect. We are still using registerLegacy() app. From my understanding PersonProvider is already added in by the Fusion Framework.
The example above is just the component without any props attached: `<PersonSelect />`
Tested on localhost

**Comment by odinr** [comment]
which version of the CLI are you using?

**Comment by Jonathanio123** [comment]
These are the Fusion packages we are using in package.json
```
        "@equinor/fusion": "^3.4.11",
        "@equinor/fusion-components": "^2.10.8",
        "@equinor/fusion-framework-module-navigation": "^2.1.2",
        "@equinor/fusion-framework-react": "^5.3.2",
        "@equinor/fusion-framework-react-app": "^4.1.9",
        "@equinor/fusion-framework-react-module-context": "^6.0.15",
        "@equinor/fusion-react-button": "^0.8.1",
        "@equinor/fusion-react-icon": "^0.2.15",
        "@equinor/fusion-react-markdown": "^0.2.0",
        "@equinor/fusion-react-person": "^0.5.1",
        "@equinor/fusion-react-side-sheet": "^1.0.1",
        "@equinor/fusion-react-styles": "^0.5.5",
```

When you say CLI I'm assuming you mean this package `@equinor/fusion-framework-cli`, we don't have it installed. Tried to simply install it and run the app, but does not seem to have changed anything.

**Comment by Jonathanio123** [comment]
So it seems we can't mix the old PersonPickers with the new PersonSelect because the new PersonSelect need the CLI framework, while the old PersonPicker do not support the new framework.

**Comment by aigelonic** [comment]
We are observing the same in our apps: `Error: No resolver resolved the request`

We are using the "old" CLI `"@equinor/fusion-cli": "^3.1.0",` and are trying to migrating by doing small steps; e.g. small PRs migrating single components at a time.

**Comment by eikeland** [comment]
Closing since its working in fusion-cli and fusion-framework-cli now.
