### ISSUE TITLE
SideSheet closing if releasing left click outside it

### ISSUE THREAD

**Issue by Jonathanio123** [equinor/fusion-react-components#989]
**Describe the bug**
Left clicking something, holding it down then releasing left click outside of the side-sheet closes it.

**To Reproduce**
Click inside the sidesheet
Drag mouse outside
Release click 
sidesheet closes

**Expected behavior**
Nothing happens and the SideSheet remains open.

**Screenshots**
![PowerToys_2scVkHKM2e](https://github.com/equinor/fusion-react-components/assets/73334350/aa71593f-bce8-4058-94cd-8a76d29fe4ea)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 117.0.2045.47 (Official build) (64-bit)

**Additional context**
Maybe this is intended behavior?

**Comment by odinr** [comment]
@Noggling is this something worth fixing?

i guess the click outside only listens to click, not onmouse down pluss up and compares target?

**Comment by eikeland** [comment]
Seems to be working in latest version
